import bcrypt from 'bcryptjs';
const data = {
    users: [
      {
        name: 'John',
        email: 'admin@example.com',
        password: bcrypt.hashSync('123456'),
        isAdmin: true,
      },
      {
        name: 'Jane',
        email: 'user@example.com',
        password: bcrypt.hashSync('123456'),
        isAdmin: false,
      },
      {
        name: 'Soumya',
        email: 'soumya@gmail.com',
        password: bcrypt.hashSync('123456'),
        isAdmin: true,
      },
    ],
    products: [
      {
        name: 'Crime and Punishment',
        slug: 'crime-and-punishment',
        category: 'Fiction Novel',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855347/bibliophile%20product%20photos/fyodor_zp2heb.jpg',
        price: 4.86,
        author: 'Fyodor Dostoyevsky',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Dostoyevsky&apos;s great novel of damnation and redemption evokes a world where the lines between innocence and corruption, good and evil, blur. It tells the story of Raskolnikov, a destitute and desperate former student, who wanders through the slums of St Petersburg and commits a random murder without remorse or regret. He imagines himself to be beyond conventional moral laws. But as he embarks on a dangerous game of cat and mouse with a police investigator, Raskolnikov is pursued by the growing voice of his conscience and finds the noose of his own guilt tightening around his neck.',
      },
      {
        name: 'War & Peace',
        slug: 'war-and-peace',
        category: 'Fiction Novel',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855348/bibliophile%20product%20photos/leo_zvfomn.jpg',
        price: 4.65,
        author: 'Leo Tolstoy',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Life did not stop and one had to live.... July 1805, St Petersburg, Russia: A country on the brink of attack. a city on the threshold of war and disruption. Five Russian families will find out just how their lives are going to entangle during the ensuing years of war and peace.. Opening at Anna Pavlovna?s soirée, Tolstoy?s War and Peace introduces you to characters such as the misfit, illegitimate son Pierre, the analytical and loner Prince Andrew, the sexually alluring Helene and the impulsive and lively Natasha, who plays the pivotal role?whose minds and actions prove to be the laboratory where Tolstoy, with a psychologist?s deftness and an artist?s vision, lays bare the frailties and manias that make up the human psyche. An explosive tale of epic proportions, War and Peace, one of the best known Russian historical novels, is as much a story of love and adultery as it is of war and death. with a deep insight into the war-stricken Russia, it underlines the irrational motives of human behavior in both war and peace.',
      },
      {
        name: 'How the Steel was tempered',
        slug: 'how-the-steel-was-tempered',
        category: 'Fiction Novel',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855350/bibliophile%20product%20photos/steel_of1dps.jpg',
        price: 7.19,
        author: 'Nikolai Ostrovsky',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'A classic novel arising from the Soviet Union in the thirties, How the Steel Was Tempered is a fictionalized account of author Nikolai Ostrovsky&apos;s experiences in fighting for the Bolsheviks during the Civil War and his difficulty in overcoming crippling injuries after the war ended. Centering on a young man named Pavel Korchagin, How the Steel Was Tempered follows his journey from ill-mannered malcontent through to disciplined soldier of the revolution, in the process coming to epitomize the ideal of the New Man.  How the Steel Was Tempered is presented here as a special edition by author J.T. Marsh as a means of preserving and disseminating a classic piece of working class literature. As part of the rich history of such literature, How the Steel Was Tempered is invaluable in embodying the constant struggle of the working class to be the masters of their own destiny.',
      },
      {
        name: 'Mastering Bolshevism',
        slug: 'mastering-bolshevism',
        category: 'Political Philosophy',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855350/bibliophile%20product%20photos/stalin_qtd6bp.jpg',
        price: 8.97,
        author: 'Joseph Stalin',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Stalin&apos;s fight against wreckers and Trotskyists comes to the fore in "Mastering Bolshevism". First published in 1937, this book documents struggles in the USSR and its Communist Party in the run up to World War II. Also includes Stalin&apos;s speech to voters.',
      },
      {
        name: 'The Prison Letters of Fidel Castro',
        slug: 'the-prison-letters-fidel',
        category: 'Political Philosophy',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855347/bibliophile%20product%20photos/fidel_qumptu.jpg',
        price: 2.04,
        author: 'Fidel Castro',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Early in Ann Louise Bardach&apos;s Cuban voyage she came across Cartas de Presidio or The Prison Letters of Fidel Castro. Edited by Luis Conte Aguero, who was the recipient of most of these letters, they are cited in every important work from Hugh Thomas&apos; opus Cuba to Tad Szulc&apos;s Fidel biography, and everything in between and since. These twenty-one letters (nine to Conte Aguero, six to his late sister and close collaborator, Lidia, one to his wife Mirta, one to his comrade in combat, Melba Hernandez letters, one to the great scholar Jorge Manach) are regarded as the single most valuable and revelatory document regarding Fidel Castro and the Cuban Revolution. Never before published in English, these letters were written when Castro was imprisoned for his failed attack on the Moncada from 1953 to 1955 and reveal a man of spectacular ambition and steely determination. A man, who despite being incarcerated to serve a lengthy prison term, never wavers in his confidence that he will one day rule Cuba.',
      },
      {
        name: 'Communist Manifesto',
        slug: 'communist-manifesto',
        category: 'Political Philosophy',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855348/bibliophile%20product%20photos/ComMan_uu97ow.jpg',
        price: 0.93,
        author: 'Karl Marx, Friedrich Engels',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'The Communist Manifesto, originally the Manifesto of the Communist Party (German: Manifest der Kommunistischen Partei), is an 1848 pamphlet by German philosophers Karl Marx and Friedrich Engels. Commissioned by the Communist League and originally published in London just as the Revolutions of 1848 began to erupt, the Manifesto was later recognised as one of the world&apos;s most influential political documents. It presents an analytical approach to the class struggle (historical and then-present) and the conflicts of capitalism and the capitalist mode of production, rather than a prediction of communism&apos;s potential future forms.  The Communist Manifesto summarises Marx and Engels&apos; theories concerning the nature of society and politics, namely that in their own words "[t]he history of all hitherto existing society is the history of class struggles". It also briefly features their ideas for how the capitalist society of the time would eventually be replaced by socialism. In the last paragraph of the Manifesto, the authors call for a "forcible overthrow of all existing social conditions", which served as a call for communist revolutions around the world.',
      },
      {
        name: 'I Burned at the Feast: Selected Poems',
        slug: 'i-burned-at-the-Feast-selected-poems',
        category: 'Poems',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855352/bibliophile%20product%20photos/arseni_sz7x8l.jpg',
        price: 26.59,
        author: 'Arseni Tarkovsky',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Poetry. Film. Translated from the Russian by Philip Metres and Dimitri Psurtsev. "Tarkovsky now joins the ranks of Mandelstam, Akhmatova, and Brodksky. Philip Metres and Dimitri Psurtsev&apos;s translationssuccinct and allusive, stingingly direct and yet sweeping, mournful and celebratoryare marvels."PEN/Heim citation  "How does one translate the work of Russian classic, Arseny Tarkovsky? Imagine trying to translate Yeats: high style rhetoric, intense emotion, local tonalities of language, complicated historical background, the old equation of poet vs. state, the tone of a tender love lyric, all meshed into one, all exquisite in its executionand all so impossible to render again. And yet, one tries. In the case of Philip Metres and Dimitri Psurtsev, one tries brilliantly, with gusto, with passion, with attentiveness that is akin to that of a prayer, with the ear of real poets. The result? The gravity and directness of Tarkovsky&apos;s tone is brought into English without fail, it is here, honest and pained, piercing and even shy at times, like a deer that looks straight at you before it runs. Tarkovsky&apos;s ambition was to seek usthose who live after himthrough earth, through time. He does so in this brilliant translation."Ilya Kaminsky  "Arseny Tarkovsky was ten years old at the time of the Russian Revolution and died six months before the opening of the Berlin Wall. He spent his career as a poet creating elegant and starkly interior transfigurations of simple happiness and pure grief, triumphs of the individual self against the brutal realities of daily life in wartime and Communist Russia. Through this meticulous translation of his work, readers will encounter a metaphysical complex poetry, at once searing and brooding, very much in dialogue with such great Soviet poets as Osip Mandelstam and Anna Akhmatova. Tarkovsky writes of a country where &apos;we lived, once upon a time, as if in a grave, drank no tea&apos; but still succeeded in making &apos;bread from weeds,&apos; where the &apos;blue sky is dim&apos; but nonetheless manages to be the &apos;wet-nurse of dragonflies and birds.',
      },
      {
        name: 'Paradise Lost',
        slug: 'paradise-lost',
        category: 'Poems',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855351/bibliophile%20product%20photos/milton_gu9gzw.jpg',
        price: 1.60,
        author: 'John Milton',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Paradise Lost is an epic poem in blank verse by the 17th-century English poet John Milton (16081674). The first version, published in 1667, consisted of ten books with over ten thousand lines of verse. A second edition followed in 1674, arranged into twelve books (in the manner of Virgil&apos;s Aeneid) with minor revisions throughout and a note on the versification. It is considered by critics to be Milton&apos;s major work, and helped solidify his reputation as one of the greatest English poets of his time.The poem concerns the Biblical story of the Fall of Man: the temptation of Adam and Eve by the fallen angel Satan and their expulsion from the Garden of Eden. Milton&apos;s purpose, stated in Book I, is to "justify the ways of God to men Short Summary The poem is separated into twelve "books" or sections, the lengths of which vary greatly (the longest is Book IX, with 1,189 lines, and the shortest Book VII, with 640). The Arguments at the head of each book were added in subsequent imprints of the first edition. Originally published in ten books, a fully "Revised and Augmented" edition reorganized into twelve books was issued in 1674, and this is the edition generally used today.The poem follows the epic tradition of starting in medias res (Latin for in the midst of things), the background story being recounted later.Milton&apos;s story has two narrative arcs, one about Satan (Lucifer) and the other following Adam and Eve. It begins after Satan and the other rebel angels have been defeated and banished to Hell, or, as it is also called in the poem, Tartarus. In Pandæmonium, Satan employs his rhetorical skill to organise his followers; he is aided by Mammon and Beelzebub. Belial and Moloch are also present. At the end of the debate, Satan volunteers to poison the newly created Earth and God&apos;s new and most favoured creation, Mankind. He braves the dangers of the Abyss alone in a manner reminiscent of Odysseus or Aeneas. After an arduous traversal of the Chaos outside Hell, he enters God&apos;s new material World, and later the Garden of Eden.At several points in the poem, an Angelic War over Heaven is recounted from different perspectives. Satan&apos;s rebellion follows the epic convention of large-scale warfare. The battles between the faithful angels and Satan&apos;s forces take place over three days. At the final battle, the Son of God single-handedly defeats the entire legion of angelic rebels and banishes them from Heaven. Following this purge, God creates the World, culminating in his creation of Adam and Eve. While God gave Adam and Eve total freedom and power to rule over all creation, He gave them one explicit command: not to eat from the Tree of the knowledge of good and evil on penalty of death.',
      },
      {
        name: 'Dhusar Pandulipi',
        slug: 'dhusar-pandulipi',
        category: 'Poems',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855348/bibliophile%20product%20photos/jibonananda_gdlbjt.jpg',
        price: 1.33,
        author: 'Jibonananda Das',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'The book was first published in 1936.[2] This poem collection was the first successful attempt in Bengali language, that did not have Tagorian influence.',
      },
      {
        name: 'Why I am an Atheist and Other Works',
        slug: 'why-i-am-an-atheist-and-other-works',
        category: 'Autobiography',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855352/bibliophile%20product%20photos/bhagat_wdvttp.jpg',
        price: 1.47,
        author: 'Bhagat Singh',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Bhagat Singh is a name that became synonymous with revolution in Indias struggle for independence. This young boy brought about a change in the way people thought about freedom. He was well read and fought extensively for rights – his own, his comrades’ and his countrymen’s. A discussion with a friend soon turned into a matter of self-assessment for Bhagat Singh, leading to a discourse on why he chose to be an atheist. Even in the face of death at a very young age, his uncanny observation leads to his putting forth some pertinent questions. On another occasion, he was disappointed with his father’s plea in Court for his innocence and chose to write a letter to him. This book is a collection of eighteen of his valued writings from within the walls of prison and outside it, which show us the resolve in his words, and the bravery in his acts subsequently.',
      },
      {
        name: 'Playing it My Way',
        slug: 'playing-it-my-way',
        category: 'Autobiography',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855349/bibliophile%20product%20photos/sachin_q4bcz1.jpg',
        price: 5.33,
        author: 'Sachin Tendulkar, Boria Majumdar',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Playing It My Way is the autobiography of former Indian cricketer Sachin Tendulkar. It was launched on 5 November 2014 in Mumbai.[3][4][5] The book summarises Tendulkar&apos;s early days, his 24 years of international career and aspects of his life that have not been shared publicly.[6] It entered the Limca Book of Records for being the best selling adult hardback across both fiction and non-fiction categories. In India, it broke the record set by Walter Isaacson&apos;s biography of Steve Jobs for being the most pre-ordered biographical book.',
      },
      {
        name: 'The Diary of a Young Girl',
        slug: 'the-diary-of-a-young-girl',
        category: 'Autobiography',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855351/bibliophile%20product%20photos/anne_tnhajo.jpg',
        price: 1.40,
        author: 'Anne Frank',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'The Diary of a Young Girl, also known as The Diary of Anne Frank, is a book of the writings from the Dutch-language diary kept by Anne Frank while she was in hiding for two years with her family during the Nazi occupation of the Netherlands. The family was apprehended in 1944, and Anne Frank died of typhus in the Bergen-Belsen concentration camp in 1945. The diary was retrieved by Miep Gies, who gave it to Anne&apos;s father, Otto Frank, the family&apos;s only known survivor, just after the Second World War was over. The diary has since been published in more than 70 languages. First published under the title Het Achterhuis. Dagboekbrieven 14 Juni 1942 – 1 Augustus 1944 (The Annex: Diary Notes 14 June 1942 – 1 August 1944) by Contact Publishing in Amsterdam in 1947, the diary received widespread critical and popular attention on the appearance of its English language translation, Anne Frank: The Diary of a Young Girl by Doubleday & Company (United States) and Vallentine Mitchell (United Kingdom) in 1952.',
      },
      {
        name: 'The State and Revolution',
        slug: 'the-state-and-revolution',
        category: 'Political Philosophy',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855348/bibliophile%20product%20photos/lenin_n8nhsn.jpg',
        price: 3.46,
        author: 'Vladimir Lenin',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'In July 1917, when the Provisional Government issued a warrant for his arrest, Lenin fled from Petrograd; later that year, the October Revolution swept him to supreme power. In the short intervening period he spent in Finland, he wrote his impassioned, never-completed masterwork The State and Revolution. This powerfully argued book offers both the rationale for the new regime and a wealth of insights into Leninist politics. It was here that Lenin justified his personal interpretation of Marxism, savaged his opponents and set out his trenchant views on class conflict, the lessons of earlier revolutions, the dismantling of the bourgeois state and the replacement of capitalism by the dictatorship of the proletariat. As both historical document and political statement, its importance can hardly be exaggerated.',
      },
      {
        name: 'Quotations From Chairman Mao Tse-Tung',
        slug: 'quotations-from-chairman-mao-tse-tung',
        category: 'Political Philosophy',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855350/bibliophile%20product%20photos/tse_tung_pi2li8.jpg',
        price: 7.86,
        author: 'Tse-Tung Mao',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'Quotations from Chairman Mao Zedong, better known in the West as The Little Red Book, was published by the Government of the People&apos;s Republic of China from April 1964 until approximately 1976. As its title implies, it is a collection of quotations excerpted from Mao Zedong&apos;s past speeches and publications. The book&apos;s alternative title The Little Red Book was coined by the West for its pocket-sized edition, which was specifically printed and sold to facilitate easy carrying.',
      },
      {
        name: 'Swarger Niche Moha Brisingkhola',
        slug: 'swarger-niche-moha-brisingkhola',
        category: 'Political Philosophy',
        image: 'https://res.cloudinary.com/bibliophile/image/upload/v1645855354/bibliophile%20product%20photos/budhhadeb_nkr1uk.jpg',
        price: 0.67,
        author: 'Buddhadeb Bhattacharya',
        rating: 4.5,
        numReviews: 10,
        countInStock: 20,
        description: 'রীর দিচ্ছে না অনেক দিন ধরেই। চোখের সমস্যা, সঙ্গে ক্রনিক সিওপিডিতে শ্বাসকষ্টও সঙ্গী। তাতে কী! আদ্যোপান্ত কমিউনিস্টের মস্তিষ্ক তো পুরোপুরি সচল।  রোগশয্যায় বাড়িতে বসে আরও একটি বই লিখে ফেললেন প্রাক্তন মুখ্যমন্ত্রী বুদ্ধদেব ভট্টাচার্য। এবার চীন। ‘‌স্বর্গের নিচে মহাবিশৃঙ্খলা’‌। বইটি শনিবারই চলে এসেছে ন্যাশনাল বুক এজেন্সির দপ্তরে। স্বর্গের নীচে মহাবিশৃঙ্খলা শব্দবন্ধ নেওয়া হয়েছে স্ত্রী জিয়াঙ কিঙকে লেখা মাও জে দঙের একটি চিঠি থেকে। বুদ্ধবাবু বইটি উৎসর্গ করেছেন তঁার রাজনৈতিক পূর্বসুরি প্রমোদ দাশগুপ্তকে। লিখেছেন, কমরেড প্রমোদ দাশগুপ্তকে, যাঁর সঙ্গে প্রথমবার চীনে গিয়েছিলাম এবং চীনেই যাঁর আকস্মিক মৃত্যু হয়েছিল আপাদমস্তক রাজনৈতিক মানুষ বুদ্ধদেব ভট্টাচার্য। তাঁর লেখায় প্রত্যক্ষ বা পরোক্ষে রাজনীতি আসবে সেটাই স্বাভাবিক। তাই ভূমিকায় নিজেই কৈফিয়ত দিয়ে রেখেছেন এই বলে, কোনও চরিত্রের পক্ষে বা বিপক্ষে আমি দাঁড়াইনি। যে বিষয়টি বাস্তবে প্রমাণিত সেটিই সত্য, শুধু তত্ত্বে নয়— এই মার্কসীয় ধারণাকেই আমি আঁকড়ে থাকার চেষ্টা করেছি। তিনি লিখেছেন, চীনের অর্থনীতির ঠিক কী অবস্থা, রাজনীতিতেই বা চীন কতটা শক্তিধর তা নিয়ে গোটা বিশ্বেই মানুষ বিশেষ আগ্রহী। তাই সাধারণ মানুষের মনের প্রশ্নের কাছাকাছি আসতে চেয়েছেন তিনি। মোট ১৩টি অধ্যায়ে সাধারণের বোধগম্য করে বুদ্ধবাবু তুলে ধরেছেন চীনের ইতিহাস, শ্রমিকশ্রেণির উত্থান, কমিউন, সাম্যবাদ| ',
      },

      
    ],
  };
  export default data;